export const ADD_SUPPLIER_LOADING = 'ADD_PRODUCT_LOADING';
export const ADD_SUPPLIER_SUCCESS = 'ADD_SUPPLIER_SUCCESS';
export const ADD_SUPPLIER_ERR = 'ADD_SUPPLIER_ERR';

export const FETCH_SUPPLIER_LOADING = 'FETCH_SUPPLIER_LOADING';

export const FETCH_SUPPLIER_SUCCESS = 'FETCH_SUPPLIER_SUCCESS';

export const FETCH_SUPPLIER_ERR = 'FETCH_SUPPLIER_ERR';

export const CREATE_CATEGORY_LOADING = 'CREATE_CATEGORY_LOADING';
export const CREATE_CATEGORY_SUCCESS = 'CREATE_CATEGORY_SUCCESS';
export const CREATE_CATEGORY_ERR = 'CREATE_CATEGORY_ERR';

export const FETCH_CATEGORY_LOADING = 'FETCH_CATEGORY_LOADING';
export const FETCH_CATEGORY_SUCCESS = 'FETCH_CATEGORY_SUCCESS';
export const FETCH_CATEGORY_ERR = 'FETCH_CATEGORY_ERR';

//Showroom
export const ADD_SHOWROOM_LOADING = 'ADD_SHOWROOM_LOADING';
export const ADD_SHOWROOM_SUCCESS = 'ADD_SHOWROOM_SUCCESS';
export const ADD_SHOWROOM_ERR = 'ADD_SHOWROOM_ERR';

export const FETCH_SHOWROOM_LOADING = 'FETCH_SHOWROOM_LOADING';
export const FETCH_SHOWROOM_SUCCESS = 'FETCH_SHOWROOM_SUCCESS';
export const FETCH_SHOWROOM_ERR = 'FETCH_SHOWROOM_ERR';


export const UPDATE_SHOWROOM_LOADING = 'UPDATE_SHOWROOM_LOADING';
export const UPDATE_SHOWROOM_SUCCESS = 'UPDATE_SHOWROOM_SUCCESS';
export const UPDATE_SHOWROOM_ERR = 'UPDATE_SHOWROOM_ERR';

export const DELETE_SHOWROOM_LOADING = 'DELETE_SHOWROOM_LOADING';
export const DELETE_SHOWROOM_SUCCESS = 'DELETE_SHOWROOM_SUCCESS';
export const DELETE_SHOWROOM_ERR = 'DELETE_SHOWROOM_ERR';

//Ware House
export const FETCH_WAREHOUSE_LOADING = 'FETCH_WAREHOUSE_LOADING';
export const FETCH_WAREHOUSE_SUCCESS = 'FETCH_WAREHOUSE_SUCCESS';
export const FETCH_WAREHOUSE_ERR = 'FETCH_WAREHOUSE_ERR';

export const ADD_WAREHOUSE_LOADING = 'ADD_WAREHOUSE_LOADING';
export const ADD_WAREHOUSE_SUCCESS = 'ADD_WAREHOUSE_SUCCESS';
export const ADD_WAREHOUSE_ERR = 'ADD_WAREHOUSE_ERR';

export const UPDATE_WAREHOUSE_LOADING = 'UPDATE_WAREHOUSE_LOADING'
export const UPDATE_WAREHOUSE_SUCCESS = 'UPDATE_WAREHOUSE_SUCCESS'
export const UPDATE_WAREHOUSE_ERR = 'UPDATE_WAREHOUSE_ERR'

export const REMOVE_WAREHOUSE_LOADING = 'REMOVE_WAREHOUSE_LOADING'
export const REMOVE_WAREHOUSE_SUCCESS = 'REMOVE_WAREHOUSE_SUCCESS'
export const REMOVE_WAREHOUSE_ERR = 'REMOVE_WAREHOUSE_ERR'

//Product

export const ADD_PRODUCT_GROUP_LOADING = 'ADD_PRODUCT_GROUP_LOADING';
export const ADD_PRODUCT_GROUP_SUCCESS = 'ADD_PRODUCT_GROUP_SUCCESS';
export const ADD_PRODUCT_GROUP_ERR = 'ADD_PRODUCT_GROUP_ERR';

export const FETCH_PRODUCT_GROUP_LOADING = 'FETCH_PRODUCT_GROUP_LOADING';
export const FETCH_PRODUCT_GROUP_SUCCESS = 'FETCH_PRODUCT_GROUP_SUCCESS';
export const FETCH_PRODUCT_GROUP_ERR = 'FETCH_PRODUCT_GROUP_ERR';

export const ADD_MULTIPLE_PRODUCT_LOADING = 'ADD_MULTIPLE_PRODUCT_LOADING';
export const ADD_MULTIPLE_PRODUCT_SUCCESS = 'ADD_MULTIPLE_PRODUCT_SUCCESS';
export const ADD_MULTIPLE_PRODUCT_ERR = 'ADD_MULTIPLE_PRODUCT_ERR'

export const TRANSFER_PRODUCT_LOADING = 'TRANSFER_PRODUCT_LOADING';
export const TRANSFER_PRODUCT_SUCCESS = 'TRANSFER_PRODUCT_SUCCESS';
export const TRANSFER_PRODUCT_ERR = 'TRANSFER_PRODUCT_ERR';

export const FETCH_PRODUCT_LOADING = 'FETCH_PRODUCT_LOADING';
export const FETCH_PRODUCT_SUCCESS = 'FETCH_PRODUCT_SUCCESS';
export const FETCH_PRODUCT_ERR = 'FETCH_PRODUCT_ERR';

export const ADD_SINGLE_PRODUCT_LOADING = 'ADD_SINGLE_PRODUCT_LOADING';
export const ADD_SINGLE_PRODUCT_SUCCESS = 'ADD_SINGLE_PRODUCT_SUCCESS';
export const ADD_SINGLE_PRODUCT_ERR = 'ADD_SINGLE_PRODUCT_ERR';

export const DELETE_PRODUCT_LOADING = 'DELETE_PRODUCT_LOADING';
export const DELETE_PRODUCT_SUCCESS = 'DELETE_PRODUCT_SUCCESS';
export const DELETE_PRODUCT_ERR = 'DELETE_PRODUCT_ERR';

export const UPDATE_PRODUCT_LOADING = 'UPDATE_PRODUCT_LOADING';
export const UPDATE_PRODUCT_SUCCESS = 'UPDATE_PRODUCT_SUCCESS';
export const UPDATE_PRODUCT_ERR = 'UPDATE_PRODUCT_ERR';

export const SET_BARCODE = 'SET_BARCODE';
export const PRINT_BARCODE = 'PRINT_BARCODE';
export const CHANGE_BARCODE_SETTING = 'CHANGE_BARCODE_SETTING';
export const FETCH_BARCODE = 'FETCH_BARCODE';
export const BARCODE_LOADING = 'BARCODE_LOADING';
export const BARCODE_ERR = 'BARCODE_ERR';


//User

export const CREATE_USER_LOADING = 'CREATE_USER_LOADING'
export const CREATE_USER_SUCCESS = 'CREATE_USER_SUCCESS'

export const CREATE_USER_ERR = 'CREATE_USER_ERR'

export const FETCH_USER_LOADING = 'FETCH_USER_LOADING'
export const FETCH_USER_SUCCESS = 'FETCH_USER_SUCCESS'
export const FETCH_USER_ERR = 'FETCH_USER_ERR'


//Invoice

export const ADD_INVOICE_LOADING = 'ADD_INVOICE_LOADING'
export const ADD_INVOICE_SUCCESS = 'ADD_INVOICE_SUCCESS'
export const ADD_INVOICE_ERR = 'ADD_INVOICE_ERR'

export const FETCH_INVOICE_LOADING = 'FETCH_INVOICE_LOADING'
export const FETCH_INVOICE_SUCCESS = 'FETCH_INVOICE_SUCCESS'
export const FETCH_INVOICE_ERR = 'FETCH_INVOICE_ERR'

export const REMOVE_INVOICE_LOADING = 'REMOVE_INVOICE_LOADING'
export const REMOVE_INVOICE_SUCCESS = 'REMOVE_INVOICE_SUCCESS'
export const REMOVE_INVOICE_ERR = 'REMOVE_INVOICE_ERR'


//Custoemr

export const FETCH_CUSTOMER_LOADING = 'FETCH_CUSTOMER_LOADING'
export const FETCH_CUSTOMER_SUCCESS = 'FETCH_CUSTOMER_SUCCESS'
export const FETCH_CUSTOMER_ERR = 'FETCH_CUSTOMER_ERR'

export const ADD_CUSTOMER_LOADING = 'ADD_CUSTOMER_LOADING'

export const ADD_CUSTOMER_SUCCESS = 'ADD_CUSTOMER_SUCCESS'

export const ADD_CUSTOMER_ERR = 'ADD_CUSTOMER_ERR'

export const UPDATE_CUSTOMER_LOADING = 'UPDATE_CUSTOMER_LOADING'
export const UPDATE_CUSTOMER_SUCCESS = 'UPDATE_CUSTOMER_SUCCESS'
export const UPDATE_CUSTOMER_ERR = 'UPDATE_CUSTOMER_ERR'

export const REMOVE_CUSTOMER_LOADING = 'REMOVE_CUSTOMER_LOADING'
export const REMOVE_CUSTOMER_SUCCESS = 'REMOVE_CUSTOMER_SUCCESS'
export const REMOVE_CUSTOMER_ERR = 'REMOVE_CUSTOMER_ERR'


//Employee

export const CREATE_EMPLOYEE_LOADING = 'CREATE_EMPLOYEE_LOADING'
export const CREATE_EMPLOYEE_SUCCESS = 'CREATE_EMPLOYEE_SUCCESS'
export const CREATE_EMPLOYEE_ERR = 'CREATE_EMPLOYEE_ERR'

export const FETCH_EMPLOYEE_LOADING = 'FETCH_EMPLOYEE_LOADING'
export const FETCH_EMPLOYEE_SUCCESS = 'FETCH_EMPLOYEE_SUCCESS'
export const FETCH_EMPLOYEE_ERR = 'FETCH_EMPLOYEE_ERR'

export const UPDATE_EMPLOYEE_LOADING = 'UPDATE_EMPLOYEE_LOADING'
export const UPDATE_EMPLOYEE_SUCCESS = 'UPDATE_EMPLOYEE_SUCCESS'
export const UPDATE_EMPLOYEE_ERR = 'UPDATE_EMPLOYEE_ERR'

export const REMOVE_EMPLOYEE_LOADING = 'REMOVE_EMPLOYEE_LOADING'
export const REMOVE_EMPLOYEE_SUCCESS = 'REMOVE_EMPLOYEE_SUCCESS'
export const REMOVE_EMPLOYEE_ERR = 'REMOVE_EMPLOYEE_ERR'


//Business

export const FETCH_BUSINESS_LOADING = 'FETCH_BUSINESS_LOADING'
export const FETCH_BUSINESS_SUCCESS = 'FETCH_BUSINESS_SUCCESS'
export const FETCH_BUSINESS_ERR = 'FETCH_BUSINESS_ERR'


export const UPDATE_BUSINESS_LOADING = 'UPDATE_BUSINESS_LOADING'
export const UPDATE_BUSINESS_SUCCESS = 'UPDATE_BUSINESS_SUCCESS'
export const UPDATE_BUSINESS_ERR = 'UPDATE_BUSINESS_ERR'
