export const ADD_SUPPLIER_LOADING = 'ADD_PRODUCT_LOADING';
export const ADD_SUPPLIER_SUCCESS = 'ADD_SUPPLIER_SUCCESS';
export const ADD_SUPPLIER_ERR = 'ADD_SUPPLIER_ERR';

export const FETCH_SUPPLIER_LOADING = 'FETCH_SUPPLIER_LOADING';

export const FETCH_SUPPLIER_SUCCESS = 'FETCH_SUPPLIER_SUCCESS';

export const FETCH_SUPPLIER_ERR = 'FETCH_SUPPLIER_ERR';

export const CREATE_CATEGORY_LOADING = 'CREATE_CATEGORY_LOADING';
export const CREATE_CATEGORY_SUCCESS = 'CREATE_CATEGORY_SUCCESS';
export const CREATE_CATEGORY_ERR = 'CREATE_CATEGORY_ERR';

export const FETCH_CATEGORY_LOADING = 'FETCH_CATEGORY_LOADING';
export const FETCH_CATEGORY_SUCCESS = 'FETCH_CATEGORY_SUCCESS';
export const FETCH_CATEGORY_ERR = 'FETCH_CATEGORY_ERR';

export const ADD_SHOWROOM_LOADING = 'ADD_SHOWROOM_LOADING';
export const ADD_SHOWROOM_SUCCESS = 'ADD_SHOWROOM_SUCCESS';
export const ADD_SHOWROOM_ERR = 'ADD_SHOWROOM_ERR';

export const FETCH_SHOWROOM_LOADING = 'FETCH_SHOWROOM_LOADING';
export const FETCH_SHOWROOM_SUCCESS = 'FETCH_SHOWROOM_SUCCESS';
export const FETCH_SHOWROOM_ERR = 'FETCH_SHOWROOM_ERR';

export const ADD_WAREHOUSE_LOADING = 'ADD_WAREHOUSE_LOADING';
export const ADD_WAREHOUSE_SUCCESS = 'ADD_WAREHOUSE_SUCCESS';
export const ADD_WAREHOUSE_ERR = 'ADD_WAREHOUSE_ERR';

export const FETCH_WAREHOUSE_LOADING = 'FETCH_WAREHOUSE_LOADING';
export const FETCH_WAREHOUSE_SUCCESS = 'FETCH_WAREHOUSE_SUCCESS';
export const FETCH_WAREHOUSE_ERR = 'FETCH_WAREHOUSE_ERR';

//Product

export const ADD_PRODUCT_GROUP_LOADING = 'ADD_PRODUCT_GROUP_LOADING';
export const ADD_PRODUCT_GROUP_SUCCESS = 'ADD_PRODUCT_GROUP_SUCCESS';
export const ADD_PRODUCT_GROUP_ERR = 'ADD_PRODUCT_GROUP_ERR';

export const FETCH_PRODUCT_GROUP_LOADING = 'FETCH_PRODUCT_GROUP_LOADING';
export const FETCH_PRODUCT_GROUP_SUCCESS = 'FETCH_PRODUCT_GROUP_SUCCESS';
export const FETCH_PRODUCT_GROUP_ERR = 'FETCH_PRODUCT_GROUP_ERR';

export const ADD_MULTIPLE_PRODUCT_LOADING = 'ADD_MULTIPLE_PRODUCT_LOADING';
export const ADD_MULTIPLE_PRODUCT_SUCCESS = 'ADD_MULTIPLE_PRODUCT_SUCCESS';
export const ADD_MULTIPLE_PRODUCT_ERR = 'ADD_MULTIPLE_PRODUCT_ERR';

export const FETCH_PRODUCT_LOADING = 'FETCH_PRODUCT_LOADING';
export const FETCH_PRODUCT_SUCCESS = 'FETCH_PRODUCT_SUCCESS';
export const FETCH_PRODUCT_ERR = 'FETCH_PRODUCT_ERR';

export const ADD_SINGLE_PRODUCT_LOADING = 'ADD_SINGLE_PRODUCT_LOADING';
export const ADD_SINGLE_PRODUCT_SUCCESS = 'ADD_SINGLE_PRODUCT_SUCCESS';
export const ADD_SINGLE_PRODUCT_ERR = 'ADD_SINGLE_PRODUCT_ERR';

export const DELETE_PRODUCT_LOADING = 'DELETE_PRODUCT_LOADING';
export const DELETE_PRODUCT_SUCCESS = 'DELETE_PRODUCT_SUCCESS';
export const DELETE_PRODUCT_ERR = 'DELETE_PRODUCT_ERR';

export const UPDATE_PRODUCT_LOADING = 'UPDATE_PRODUCT_LOADING';
export const UPDATE_PRODUCT_SUCCESS = 'UPDATE_PRODUCT_SUCCESS';
export const UPDATE_PRODUCT_ERR = 'UPDATE_PRODUCT_ERR';

export const SET_BARCODE = 'SET_BARCODE';
export const PRINT_BARCODE = 'PRINT_BARCODE';
export const CHANGE_BARCODE_SETTING = 'CHANGE_BARCODE_SETTING';
export const FETCH_BARCODE = 'FETCH_BARCODE';
export const BARCODE_LOADING = 'BARCODE_LOADING';
export const BARCODE_ERR = 'BARCODE_ERR';
